#!/bin/bash -e

cat <<- "EOF"
# DO NOT EDIT THIS FILE BY HAND,
# it was generated by ./gen_static_conf.sh
#
worker_processes                   auto;
events
{
    worker_connections             1024;
}
http
{
    include                        mime.types;
    default_type                   application/octet-stream;
    sendfile                       on;
    keepalive_timeout              120;
    types_hash_max_size            4096;
    server_names_hash_bucket_size  128;
EOF
echo "    resolver                       ${1} valid=10s ipv6=off;"
cat <<- "EOF"
    server
    {
          listen                   80;
EOF
echo "        server_name                ${2};"
cat <<- "EOF"
        root                       /var/www;
        autoindex                  on;
        location                   ~ \.(db|sig|files)$
        {
            proxy_pass             http://mirrors$request_uri;
        }
        location                   ~ \.tar\.(xz|zst)$
        {
            try_files              $uri @pkg_mirror;
        }
        location                   @pkg_mirror
        {
            proxy_store            on;
            proxy_redirect         off;
            proxy_store_access     user:rw group:rw all:r;
            proxy_next_upstream    error timeout http_404;
            proxy_pass             http://mirrors$request_uri;
        }
    }
    upstream                       mirrors
    {
EOF
# Sets up the mirror list and proxy_pass server for each server value in mirrorlist file
INTERNAL_PORT=9001
BACKUP=""
grep -E "^\s*[Ss]erver\s*=\s*http" mirrorlist | grep -Eo "http[s]*://.*" | while read -r url; do
  echo "        server                     127.0.0.1:${INTERNAL_PORT}${BACKUP};"
  BACKUP=' backup'
  INTERNAL_PORT=`expr $INTERNAL_PORT + 1`
done
echo "    }"
INTERNAL_PORT=9001
grep -E "^\s*[Ss]erver\s*=\s*http" mirrorlist | grep -Eo "http[s]*://.*" | while read -r url; do
  echo "    server"
  echo "    {"
  echo "        listen                     127.0.0.1:${INTERNAL_PORT};"
  echo "        location                   /"
  echo "        {"
  echo "            proxy_pass             ${url}\$request_uri;"
  echo "        }"
  echo "    }"
  INTERNAL_PORT=`expr $INTERNAL_PORT + 1`
done
echo "}"